### ISSUE TITLE
Partially generating output text

### ISSUE THREAD

**Issue by savinduekanayake** [jsrozner/t5_finetune#2]
Hi ,
I'm use this T5 model finetune for text generation task. 

I have a issue of partially generating the text.

for example this is the generated text: 
"< pad > Kasun has 7 books and gave Nimal 2 of the books. How many book did Ka"

This is the full output.

- This is not the full sentence and  not end with < /s > token. 

-  Output are maximum 17 words.  Giving  model.generate( . . . , min_length=30 ) is also not working.

(only small amount of word contains sentence are giving full output sentence)
How can I fix this issue?
Thank you.

**Comment by jsrozner** [comment]
See response in this thread: https://discuss.huggingface.co/t/t5-for-conditional-generation-getting-started/1284/8
